import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/Providers/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          
          <div className="shadow-sm bg-base-100 ">
          <Navbar/>
        </div>
        <Toaster/>
        <div className=' min-h-[calc(100vh-243px)] '>
          {/* mt-16 */}
             {children}
        </div>       
        <div>
          <Footer/>
          {/* // fixed top-0 left-0 w-full z-50 */}
        </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}

